export const GalleryData = [
  {
    id: 1,
    image: "/images/blog-image.jpeg",
    slug: "the-coldest-sunset",
    title: "The Coldest Sunset",
    images:[
            "/assets/collage-img/img-1.webp",
            "/assets/collage-img/img-2.webp",
            "/assets/collage-img/img-3.webp",
            "/assets/collage-img/img-4.webp",
            "/assets/collage-img/img-5.webp",
            "/assets/collage-img/img-6.webp",
            "/assets/collage-img/img-7.webp",
            "/assets/collage-img/img-8.webp",
            "/assets/collage-img/img-9.webp",
          ],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    tags: ["photography", "travel", "winter"],
  },
  {
    id: 2,
    image: "/images/blog-image.jpeg",
    slug: "mountain-adventure",
    title: "Mountain Adventure",
     images:[
            "/assets/collage-img/img-1.webp",
            "/assets/collage-img/img-2.webp",
            "/assets/collage-img/img-3.webp",
            "/assets/collage-img/img-4.webp",
            "/assets/collage-img/img-5.webp",
            "/assets/collage-img/img-6.webp",
            "/assets/collage-img/img-7.webp",
            "/assets/collage-img/img-8.webp",
            "/assets/collage-img/img-9.webp",
          ],
    description:
      "Discover the beauty of untouched mountains and wild trails.",
    tags: ["adventure", "mountains"],
  },
  {
    id: 3,
    image: "/images/blog-image.jpeg",
    slug: "the-coldest-sunset",
    title: "The Coldest Sunset",
     images:[
            "/assets/collage-img/img-1.webp",
            "/assets/collage-img/img-2.webp",
            "/assets/collage-img/img-3.webp",
            "/assets/collage-img/img-4.webp",
            "/assets/collage-img/img-5.webp",
            "/assets/collage-img/img-6.webp",
            "/assets/collage-img/img-7.webp",
            "/assets/collage-img/img-8.webp",
            "/assets/collage-img/img-9.webp",
          ],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    tags: ["photography", "travel", "winter"],
  },
  {
    id: 4,
    image: "/images/blog-image.jpeg",
    slug: "mountain-adventure",
    title: "Mountain Adventure",
     images:[
            "/assets/collage-img/img-1.webp",
            "/assets/collage-img/img-2.webp",
            "/assets/collage-img/img-3.webp",
            "/assets/collage-img/img-4.webp",
            "/assets/collage-img/img-5.webp",
            "/assets/collage-img/img-6.webp",
            "/assets/collage-img/img-7.webp",
            "/assets/collage-img/img-8.webp",
            "/assets/collage-img/img-9.webp",
          ],
    description:
      "Discover the beauty of untouched mountains and wild trails.",
    tags: ["adventure", "mountains"],
  },
  {
    id: 5,
    image: "/images/blog-image.jpeg",
    slug: "the-coldest-sunset",
    title: "The Coldest Sunset",
     images:[
            "/assets/collage-img/img-1.webp",
            "/assets/collage-img/img-2.webp",
            "/assets/collage-img/img-3.webp",
            "/assets/collage-img/img-4.webp",
            "/assets/collage-img/img-5.webp",
            "/assets/collage-img/img-6.webp",
            "/assets/collage-img/img-7.webp",
            "/assets/collage-img/img-8.webp",
            "/assets/collage-img/img-9.webp",
          ],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    tags: ["photography", "travel", "winter"],
  },
  {
    id: 6,
    image: "/images/blog-image.jpeg",
    slug: "mountain-adventure",
    title: "Mountain Adventure",
     images:[
            "/assets/collage-img/img-1.webp",
            "/assets/collage-img/img-2.webp",
            "/assets/collage-img/img-3.webp",
            "/assets/collage-img/img-4.webp",
            "/assets/collage-img/img-5.webp",
            "/assets/collage-img/img-6.webp",
            "/assets/collage-img/img-7.webp",
            "/assets/collage-img/img-8.webp",
            "/assets/collage-img/img-9.webp",
          ],
    description:
      "Discover the beauty of untouched mountains and wild trails.",
    tags: ["adventure", "mountains"],
  },
];
